[theme]
primaryColor="#FFA500"
backgroundColor="#1E1E2F"
secondaryBackgroundColor="#2D2D3A"
textColor="#FFFFFF"
font="sans serif"

[server]
headless=true
enableCORS=false
[theme]
primaryColor = "#FFA500"
backgroundColor = "#1E1E2F"
secondaryBackgroundColor = "#2D2D3A"
textColor = "#FFFFFF"
font = "sans serif"